export const iconIds = {
  tracks: 'icon-tracks',
  albums: 'icon-albums',
  playbackQueue: 'icon-playback-queue',
  settings: 'icon-settings',
  play: 'icon-play',
  pause: 'icon-pause',
  prev: 'icon-prev',
  next: 'icon-next',
  dots: 'icon-dots',
  shuffle: 'icon-shuffle',
  mute: 'icon-volume_mute',
  mid: 'icon-volume_mid',
  full: 'icon-volume_full',
  repeat: 'icon-repeat',
  artists: 'icon-artists',
  like: 'icon-like',
  delete: 'icon-delete',
  repeatOne: 'icon-repeat-one',
  home: 'icon-home',
  search: 'icon-search',
  empty: 'icon-empty',
  checkmark: 'icon-checkmark',
  add: 'icon-add',
  close: 'icon-close',
  warning: 'icon-warning',
};
